version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![published](https://static.production.devnetcloud.com/codeexchange/assets/images/devnet-published.svg)](https://developer.cisco.com/codeexchange/github/repo/qzx/terraform-aci-l3out)
  # Terraform ACI L3Out Module
  Manages ACI L3Out
  Location in GUI:
  `Tenants/Networking/L3Outs`
  ## Examples
  ### Minimal L3Out config
  ```hcl
  {{ include "./examples/minimal/main.tf" }}
  ```

  ### L3Out over dual VPC in two pods with OSPF
  ```hcl
  {{ include "./examples/vpc/main.tf" }}
  ```

  ### Dual L3Out with BGP 
  ```hcl
  {{ include "./examples/ha-mpls/main.tf" }}
  ```
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false